version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./loads.sql:/docker-entrypoint-initdb.d/loads.sql
    environment:
      POSTGRES_USER: robotadmin
      POSTGRES_PASSWORD: makehappyrobotgreat
      POSTGRES_DB: happyrobot
      POSTGRES_INITDB_ARGS: "--no-locale --encoding=UTF-8"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  load-service:
    image: happyrobot-loads
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    env_file: .env
    command: python find_available_loads.py
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network

  carrier-service:
    image: happyrobot-carriers
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file: .env
    command: python verify_carrier.py
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network

  reverse-proxy:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ~/ssl-certs:/etc/ssl/certs
    depends_on:
      - load-service
      - carrier-service
    networks:
      - app-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge